parameters:
#    hanky_paplek.example.class: Hanky\PaplekBundle\Example

services:
#    hanky_paplek.example:
#        class: %hanky_paplek.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
